{
  config,
  pkgs,
  lib ? pkgs.lib,
  ...
}:
let
  monitors = config.hardwareConf.monitors;
in
{
  programs.mangohud = {
    enable = true;
    settings = lib.mkMerge [
      (lib.mkIf (builtins.hasAttr "refresh_rate" monitors.primary) {
        # max fps = monitor refresh rate
        fps_limit = monitors.primary.refresh_rate;
      })

      {
        ################### File Generated by GOverlay ###################

        toggle_fps_limit = "F1";
        vsync = 0;
        gl_vsync = -1;
        legacy_layout = false;
        gpu_stats = true;
        graphs = "gpu_load,gpu_core_clock,cpu_load";
        gpu_temp = true;
        gpu_load_change = true;
        gpu_load_value = "50,90";
        gpu_load_color = "FFFFFF,FF7800,CC0000";
        gpu_text = "GPU";
        cpu_stats = true;
        cpu_temp = true;
        cpu_load_change = true;
        core_load_change = true;
        cpu_load_value = "50,90";
        cpu_load_color = "FFFFFF,FF7800,CC0000";
        cpu_color = "2e97cb";
        cpu_text = "CPU";
        io_color = "a491d3";
        vram = true;
        vram_color = "ad64c1";
        ram = true;
        ram_color = "c26693";
        fps = true;
        engine_color = "eb5b5b";
        gpu_color = "2e9762";
        wine_color = "eb5b5b";
        frame_timing = 1;
        frametime_color = "00ff00";
        media_player_color = "ffffff";
        no_display = true;
        background_alpha = 0.4;
        font_size = 20;
        font_file = "${pkgs.dejavu_fonts}/share/fonts/truetype/DejaVuSans.ttf";
        background_color = "020202";
        position = "top-left";
        text_color = "ffffff";
        round_corners = 5;
        toggle_hud = "Shift_R+F12";
        toggle_logging = "Shift_L+F2";
        upload_log = "F5";
        # output_folder=/home/alex
        media_player_name = "spotify";
      }
    ];
  };
}
